# Generated by Django 4.2.1 on 2023-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='phone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
